---
services:
  ungoogled-chromium:
    build: .
    container_name: ungoogled-chromium
    security_opt:
      - seccomp:unconfined
    cap_add:
      - SYS_ADMIN
      - SYS_RAWIO
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - WAYLAND_DISPLAY=${WAYLAND_DISPLAY}
      - XDG_RUNTIME_DIR=/run/user/1000
      - UDEV=1
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
      - NVIDIA_DISABLE_REQUIRE=1
    volumes:
      - ~/.config/containers/ungoogled-chromium:/config
      - ${XDG_RUNTIME_DIR}/${WAYLAND_DISPLAY}:/run/user/1000/${WAYLAND_DISPLAY}
      - /run/dbus/system_bus_socket:/run/dbus/system_bus_socket
    devices:
      - /dev/bus/usb:/dev/bus/usb
      - /dev/hidraw1:/dev/hidraw1
      - /dev/hidraw2:/dev/hidraw2
    shm_size: "2gb"
    restart: unless-stopped
    runtime: nvidia
